services:
  app:
    build: .
    container_name: salary-app
    env_file:
      - .env
    environment:
      API_KEY_FILE: /run/secrets/api_key
    secrets:
      - api_key
    ports:
      - "8002:8001"
    volumes:
      - salary-logs:/app/logs
    restart: unless-stopped

secrets:
  api_key:
    file: ./api_key.secret

volumes:
  salary-logs:
